### PR TITLE
[Feature]: added new resources to learn devops

### LINKED ISSUE #12: Resources to Learn Devops

### PR DESCRIPTION
**Pull request by Rohit-Sharmaa**
Description
This pr is all about adding new resources about devops
I have added course , books and blog from where you can learn devops

Fixes #12

### CODE REVIEW

**Comment by Rohit-Sharmaa** [comment]
@DhanushNehru  I have added some new resources please check it our.

**Comment by DhanushNehru** [comment]
Please make the alignment proper @Rohit-Sharmaa

**Comment by Rohit-Sharmaa** [comment]
@DhanushNehru  not able to understand which alignment you are taking about 
Screenshot 2023-10-06 225201

I have added my pr image can you give me some details in which part the alignment is not correct??

**Comment by DhanushNehru** [comment]
The last commit looks fine @Rohit-Sharmaa

**Review by DhanushNehru — APPROVED** [review]

**Pull request merged**
